Numpy stands for Numerical Python, we encounter large datasets in ML so in order to make the processing of that data smooth and easy we will use Numpy

Numpy arrays offer many mathematical operations over the array then a normal list or tuple can, the operations that we do on Numpy arrays are much faster than in the python list.

In [1]:
import  numpy as np

List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
py_list = [i for i in range(10000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.004926859000000228


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0023987950000003977


#Numpy arrays

In [5]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)  #Numpy arrays are similar to matrces

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a one dimensional array

a = np.array([1,2,4,5])
print(a)

[1 2 4 5]


In [10]:
a.shape #this will give the number of rows and columns that our numpy array will contain

(4,)

In [18]:
b = np.array([[1,23,3,4],[23,45,67,6]])
print(b)  #we cannot create inhomegenious numpy array

[[ 1 23  3  4]
 [23 45 67  6]]


In [15]:
b.shape

(2, 4)

In [19]:
c = np.array([[1,2,3],[3,4,5]] , dtype= float)
print(c)

[[1. 2. 3.]
 [3. 4. 5.]]


*Intital placeholders in Numpy arrays*

In [20]:
#create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#create a numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#array of a particular value
z= np.full((4,4) , 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
#creating an identity matrix
a== np.eye(4)
print(a)

[1 2 4 5]


In [26]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.44680972 0.85901321 0.82866872 0.50925392]
 [0.93848821 0.20461413 0.20887525 0.15368652]
 [0.52979379 0.67339382 0.04683738 0.46381606]]


In [27]:
#create an numpy array woth integers within a specific range

c= np.random.randint(10,100,(2,5))
print(c)

[[62 48 48 38 53]
 [18 27 45 12 66]]


In [28]:
#array with evenly spaced value from 10 to 30 with 6 elements in it
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [29]:
#array with evenly spaced values specifying the steps that is from where to start
#and where till where to go with the space to take

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [30]:
#converting a list ot a numpy array
list2 = [10,30,50,60]

np_array = np.asarray(list2)
print(np_array)
type(np_array)


[10 30 50 60]


numpy.ndarray

#Analysing a Numpy array#

In [31]:
c= np.random.randint(10,90,(5,5))
print(c)

[[12 84 43 25 55]
 [38 26 18 14 49]
 [85 20 80 23 49]
 [41 30 31 56 19]
 [19 55 85 22 54]]


In [32]:
#array dimension
print(c.shape)

(5, 5)


In [33]:
#number of dimensions
print(c.ndim)

2


In [34]:
#number of elemennts in an array
print(c.size)

25


In [35]:
#checking the data type of the values int he array
print(c.dtype)

int64


mathematical operations on a np array

In [37]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  #it will just concatenate

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [38]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 1 9]
 [1 7 5]
 [1 1 2]]
[[18 10 18]
 [15 11 16]
 [15 14 14]]


In [40]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[[22 11 27]
 [16 18 21]
 [16 15 16]]
[[ 72  10 162]
 [ 15  77  80]
 [ 15  14  28]]
[[-14  -9  -9]
 [-14  -4 -11]
 [-14 -13 -12]]
[[0.22222222 0.1        0.5       ]
 [0.06666667 0.63636364 0.3125    ]
 [0.06666667 0.07142857 0.14285714]]


You can also do the above arithmatic operations byusing funcitons below also

In [42]:
print(np.add(a,b))
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[22 11 27]
 [16 18 21]
 [16 15 16]]
[[ 72  10 162]
 [ 15  77  80]
 [ 15  14  28]]
[[-14  -9  -9]
 [-14  -4 -11]
 [-14 -13 -12]]
[[0.22222222 0.1        0.5       ]
 [0.06666667 0.63636364 0.3125    ]
 [0.06666667 0.07142857 0.14285714]]


#Array Manipulation

In [44]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 2 4]
 [1 2 9]]
(2, 3)


In [45]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 1]
 [2 2]
 [4 9]]
(3, 2)


In [46]:
trans2 = np.transpose(trans)
print(trans2)

[[5 2 4]
 [1 2 9]]


In [47]:
trans3 = array.T
print(trans3)

[[5 1]
 [2 2]
 [4 9]]


In [48]:
#reshaping a array
a = np.random.randint(0,10,(4,5))
print(a)
print(a.shape)

[[9 9 7 3 8]
 [3 8 3 4 4]
 [3 1 6 4 4]
 [8 3 5 8 2]]
(4, 5)


In [52]:
b = a.reshape(10,2)
print(b)
print(b.shape)  #note the numebr of element in both matrices a and b should be same
#that is there m x n should be same

[[9 9]
 [7 3]
 [8 3]
 [8 3]
 [4 4]
 [3 1]
 [6 4]
 [4 8]
 [3 5]
 [8 2]]
(10, 2)
